---

---

```{r}
library(tidyverse)
```

```{r}
models_dir <- '/project2/haky/temi/projects/TFPred-snakemake/output/models'
```


```{r}
#valid_dates <- c('2023-11-14', '2023-12-01')

valid_dates <- c('2024-04-23')

logistic_models <- list.files(models_dir, full.names = TRUE, recursive = T) %>% sapply(., function(each_model){
    if(endsWith(each_model, ".logistic.rds") && grepl('aggByCollect_', each_model, fixed=T) && any(sapply(valid_dates, grepl, x=each_model, fixed=TRUE))){
        return(each_model)
    }
}) %>% Filter(Negate(is.null), .)
```


```{r}
nn <- names(logistic_models) %>% base::strsplit(., split="/") %>% sapply(., function(each_name){
    each_name[length(each_name)]
}) %>% base::strsplit(., '\\.') %>% sapply(., function(each_name){
    gsub('aggByCollect_', '', each_name[1])
})
```


```{r}
if(length(unique(nn)) == length(nn)){
    names(logistic_models) <- nn
    do.call(rbind, logistic_models) %>%
        as.data.frame() %>%
        tibble::rownames_to_column('model') %>%
        setNames(nm=c('model', 'path')) %>%
        data.table::fwrite(., file='/project2/haky/temi/projects/enpact-predict-snakemake/metadata/enpact_models.txt', row.names=F, col.names=T, quote=F, sep='\t')
}
```



```{r}
enpact_db <- readRDS("/project2/haky/temi/projects/enpact-predict-snakemake/output/baca_2024-03-27/baca_2024-03-27.enpact_scores.array.rds.gz")
dimnames(enpact_db)
```

```{r}
enpact_db[, , 'AR_Prostate'][1:5, 1:5]
```



```{r}
models_dir <- '/beagle3/haky/users/temi/projects/TFPred-snakemake/data/ENPACT_734_2024-07-26/models'
```


```{r}
#valid_dates <- c('2023-11-14', '2023-12-01')

valid_dates <- c('2024-07-26')

logistic_models <- list.files(models_dir, full.names = TRUE, recursive = T) %>% 
    sapply(., function(each_model){
        if(endsWith(each_model, ".logistic.rds") && any(sapply(valid_dates, grepl, x=each_model, fixed=TRUE))){
            if(file.info(each_model)$size > 0){
                return(each_model)
            }
        }
    }) %>% Filter(Negate(is.null), .)
```


```{r}
nn <- names(logistic_models) %>% base::strsplit(., split="/") %>% sapply(., function(each_name){
    each_name[length(each_name)]
}) %>% base::strsplit(., '\\.') %>% sapply(., function(each_name){
    gsub(paste0('_', valid_dates), '', each_name[1])
})
```


```{r}
if(length(unique(nn)) == length(nn)){
    names(logistic_models) <- nn
    do.call(rbind, logistic_models) %>%
        as.data.frame() %>%
        tibble::rownames_to_column('model') %>%
        setNames(nm=c('model', 'path')) %>%
        data.table::fwrite(., file='/beagle3/haky/users/temi/projects/TFPred-snakemake/metadata/enpact_734_models.txt', row.names=F, col.names=T, quote=F, sep='\t')
}
```