
---
# directories
cistrome_data_dir: '/project2/haky/Data/TFXcan/cistrome/raw/human_factor' # where are the cistrome bed files
pipeline_dir: '/project2/haky/temi/projects/TFPred-snakemake'
dataset: 'cistrome_nonCancer_47' # change this variable name 
date: "2024-05-20" #"2023-11-19" #"2023-11-14"
TF_table: '/project2/haky/Data/TFXcan/cistrome/raw/human_factor_full_QC.txt' # where is the cistrome metadata file
metadata: "/project2/haky/temi/projects/TFPred-snakemake/metadata/short_metadata.txt"
delete_enformer_outputs: False # should you delete enformer predictions after aggregating them? Saves disk space
use_homer_motifs: True
scratch_dir: "/scratch/midway3/temi"
train_by_chromosome: True

# dcids
dcids: "56122,56107,56111,56115,56124,56119,56390,56109,56125,56118,56123,56121,50058,76206,50057,56113,50056,56112,56116,56108,56110,56106,50060,56392,56391,50059,50051,56114,50052,50049,72971,76205,50054,56117,56120,2986,50055,50050,50053,72975,72970,56389,72974,56395,56388,56393,56394"

genome:
  fasta: "/project2/haky/Data/hg_sequences/hg38/Homo_sapiens_assembly38.fasta"

homer:
  dir: '/project2/haky/temi/software/homer'
  scanMotifsGenome: '/project2/haky/temi/software/homer/bin/scanMotifGenomeWide.pl'
  genome: '/project2/haky/temi/software/homer/data/genomes/hg38'

rscript: "/beagle3/haky/users/shared_software/TFXcan-pipeline-tools/bin/Rscript"

enformer: 
  base_directives: "config/enformer_base.yaml"
  model: "/project2/haky/Data/enformer/raw"
  predict: "/beagle3/haky/users/shared_pipelines/enformer_pipeline_aggregate/scripts/enformer_predict.py"
  aggregate: "/beagle3/haky/users/shared_pipelines/enformer_pipeline_aggregate/scripts/aggregate/aggregate.py"
  aggtype: "aggByCollect"
...
