
---
# directories
cistrome_data_dir: '/project2/haky/Data/TFXcan/cistrome/raw/human_factor' # where are the cistrome bed files
pipeline_dir: '/project2/haky/temi/projects/TFPred-snakemake'
dataset: 'cistrome' # change this variable name 
date: "2023-11-20" #"2023-11-14"
TF_table: '/project2/haky/Data/TFXcan/cistrome/raw/human_factor_full_QC.txt' # where is the cistrome metadata file
metadata: "/project2/haky/temi/projects/TFPred-snakemake/metadata/one_tf_tissue.txt"
delete_enformer_outputs: False

genome:
  fasta: "/project2/haky/Data/hg_sequences/hg38/Homo_sapiens_assembly38.fasta"

homer:
  dir: '/project2/haky/temi/software/homer'
  scanMotifsGenome: '/project2/haky/temi/software/homer/bin/scanMotifGenomeWide.pl'
  genome: '/project2/haky/temi/software/homer/data/genomes/hg38'

rscript: "/beagle3/haky/users/shared_software/TFXcan-pipeline-tools/bin/Rscript"

enformer: 
  base_directives: "config/enformer_base.yaml"
  model: "/project2/haky/Data/enformer/raw"
  predict: "/beagle3/haky/users/shared_pipelines/enformer_pipeline_aggregate/scripts/enformer_predict.py"
  aggregate: "/beagle3/haky/users/shared_pipelines/enformer_pipeline_aggregate/scripts/aggregate/aggregate.py"
  aggtype: "aggByCollect"
...
