
---
# directories
pipeline_dir: '/project2/haky/temi/projects/TFPred-snakemake'
dataset: 'cistrome' # change this variable name 
date: "2024-06-08" #"2023-11-19" #"2023-11-14"

delete_enformer_outputs: False # should you delete enformer predictions after aggregating them? Saves disk space
use_homer_motifs: True
scratch_dir: "/scratch/midway3/temi"
train_by_chromosome:
  condition: True
  test: ['chr9', 'chr22']
  # logically, training will the done on the other chromosomes

# data information
models_config: "/project2/haky/temi/projects/TFPred-snakemake/metadata/enpact_models_to_train.short.yaml"
models_metadata: "/project2/haky/temi/projects/TFPred-snakemake/metadata/enpact_models_to_train.short.tsv"

genome:
  fasta: "/project2/haky/Data/hg_sequences/hg38/Homo_sapiens_assembly38.fasta"

peaks:
  directory: /project2/haky/Data/TFXcan/cistrome/raw/human_factor' # where are the cistrome bed files

homer:
  dir: '/project2/haky/temi/software/homer'
  motifs_database: /project2/haky/temi/software/homer/motifs
  scanMotifsGenome: '/project2/haky/temi/software/homer/bin/scanMotifGenomeWide.pl'
  genome: '/project2/haky/temi/software/homer/data/genomes/hg38'

rscript: "/beagle3/haky/users/shared_software/TFXcan-pipeline-tools/bin/Rscript"

enformer: 
  base_directives: "config/enformer_base.yaml"
  model: "/project2/haky/Data/enformer/raw"
  predict: "/beagle3/haky/users/shared_pipelines/enformer_pipeline_aggregate/scripts/enformer_predict.py"
  aggregate: "/beagle3/haky/users/shared_pipelines/enformer_pipeline_aggregate/scripts/aggregate/aggregate.py"
  aggtype: "aggByCollect"
...
