cluster:
  mkdir -p logs/slurm_logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --mem={resources.mem_mb}
    --time={resources.time}
    --account={resources.account}
    --job-name=smk-{rule}-{params.jobname}
    --output=logs/slurm_logs/{rule}/{params.jobname}.out
    --error=logs/slurm_logs/{rule}/{params.jobname}.err
    --exclusive # very important 
default-resources:
  - partition=caslake
  - time="02:00:00"
  - tmpdir="/scratch/midway3/temi"
  - account="pi-haky"
restart-times: 0
max-jobs-per-second: 20
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 100
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: False